### ISSUE TITLE
Cold Structure placement

### ISSUE THREAD

**Issue by SafeOfArsenal** [SmartStreamLabs/Create-Structures-Arise-Bugs#1]
![2024-09-08_01 30 14](https://github.com/user-attachments/assets/2aac4a85-852e-499f-b051-4220bb35771e)
is there a way you could fix this?

**Comment by SmartStreamLabs** [comment]
Thank you for creating an issue. 

This is unfortunately another bug in world generation. luckily we are currently working on a fix! (135.8.6 bug fix update)

This will be published soon.
