### ISSUE TITLE
Crash structure tank version 1.201

### ISSUE THREAD

**Issue by xXjojojXx** [SmartStreamLabs/Create-Structures-Arise-Bugs#2]
[Neues Textdokument.txt](https://github.com/user-attachments/files/17083204/Neues.Textdokument.txt)
as soon as I use a real mod from them the server crashes after a certain time because it tries to set structure tank I have tried different server versions Minecraft Forge / Hybrid and the result is always the same if I remove the mod then this error no longer occurs

**Comment by xXjojojXx** [comment]
ERROR09:04:31
Unknown structure start: create_structures_arise:createfluidtank

**Comment by xXjojojXx** [comment]
I have now tried it as follows: if I leave it in, it crashes if I remove the mod, the server starts, it is definitely due to some structure. My guess is that it is with the tank.

**Comment by xXjojojXx** [comment]
FluidTankBlockEntity thrown inside the Create mod when attempting to access a null field (this.f_58857_), causing a NullPointerException during feature placement​

**Comment by SmartStreamLabs** [comment]
heya! May I ask which create version you are playing with? we heard that the latest version of create breaks all ( addons ). If you're playing with the latest version of create, try downgrading it. Support, Mei:)

**Comment by xXjojojXx** [comment]
I also tried it with the previous version exactly the same problem so I looked closely at the error it somehow has exactly problems with this tank

**Comment by SmartStreamLabs** [comment]
Can you explain in steps how the crash happened?

Do you use /locate ?

![Minecraft Forge_ 1 20 1 - Singleplayer 21-9-2024 11_27_37](https://github.com/user-attachments/assets/1e79fffc-d82e-40c4-8b7c-0d7c5ce27aab)

**Comment by xXjojojXx** [comment]
The problem occurs on normal as well as on hybrid if the chunk has not yet been changed and a player is nearby, this crash occurs but does not always occur, it is rather sporadic and random

**Comment by SmartStreamLabs** [comment]
Do you have a crash report?

**Comment by xXjojojXx** [comment]
yes I put it at the top ---> New text document.txt

**Comment by SmartStreamLabs** [comment]
It looks like the mods: ( create ) & ( moderfix ) don't work well together.

Our tip to you is to create a ticket on the create github page itself. We cannot adjust anything in terms of codes for the (fluid tank)

Here is the link to the create issue (github) https://github.com/Creators-of-Create/Create/issues

hopefully they can solve it for you! Mei

**Comment by xXjojojXx** [comment]
Thank you for your help. I will open a ticket there because the problem also occurs when it is a Rainer forge server

**Comment by SmartStreamLabs** [comment]
No problem! feel free to open a new ticket if you have a bug or problem.
