### ISSUE TITLE
I got empty chests in every Create Structure

### ISSUE THREAD

**Issue by philphil2002** [SmartStreamLabs/Create-Structures-Arise-Bugs#3]
I have made almost all Create Mod addons in a modpack. Now I have empty crates in every Create: Structures arise structure. I also have Lootr inside which marks lootchests for me. It doesn't work with or without Lootr.
If u need more information write me.
If you can fix it so that I finally have loot in the crates again, I would be very grateful.

**Comment by SmartStreamLabs** [comment]
Thank you for the report. what version of create are you using ?

**Comment by philphil2002** [comment]
I am using the version 1.20.1-0.5.1.j

**Comment by SmartStreamLabs** [comment]
Alright. can you downgraded 2 versions  of the create mod and test it again? most of the create structure mods doesn't work with the latest create version.

Link: https://www.curseforge.com/minecraft/mc-mods/create/files/4835191

**Comment by philphil2002** [comment]
When I downgrade it two versions a few other mods don't work in the modpack. I turn off the mods and try it but unfortunately that is not a solution to the problem. I don't want to have to switch off other important mods to play this.

**Comment by philphil2002** [comment]
I have just tested it and even with the downgrade it does not work.

**Comment by philphil2002** [comment]
I have just tested the new update and as far as I can see everything is working again.
Thank you very much.
