### ISSUE TITLE
Startup Crash Modpack

### ISSUE THREAD

**Issue by ZeroTronix** [SmartStreamLabs/Create-Structures-Arise-Bugs#4]
Hey i am putting a modpack together atm and when i add your mod it crashes on startup heres the log idk what is really causing the issue. 
https://mclo.gs/XxaafKJ
Eventually you find something

**Comment by SmartStreamLabs** [comment]
I have the following questions for you:

Which version are you playing (1.20.1 / 1.19.2)

Which version of create are you using?

And have you tried loading without our mod?

**Comment by ZeroTronix** [comment]
To Answer your Questions
1.20.1 and create 0.5.1j
I tryed it without it and it was working then ... now the other thing i testet a little and it is not your mod that is causing issues.
Exactly when i have over 165 mods active it crashes on startup no matter what mods are active. When i go come to 164 it is working.
So i am trying to figure that out now >.<

... Minecraft

**Comment by SmartStreamLabs** [comment]
Maybe this will help

modernfix,pl:mixin:APP:modernfix-forge.mixins.json:core.BootstrapMixin from mod modernfix,pl:mixin:APP:modernfix-forge.mixins.json:core.BootstrapClientMixin from mod modernfix,pl:mixin:APP: connectormod.mixins.json:registries.BootstrapMixin from mod connectormod,pl:mixin:APP:fabric-registry-sync-

**Comment by ZeroTronix** [comment]
It was the Connector Extra mod i had installed it just caused issues with my Forge/Fabric modpack so yeah solved ^^

**Comment by SmartStreamLabs** [comment]
Alrighty! enjoy playing again :)
